### ISSUE TITLE
Exception during startup with open-liberty

### ISSUE THREAD

**Issue by ashu-mehra** [WASdev/sample.daytrader7#16]
I followed the process for building daytrader application as described [here](https://github.com/WASdev/sample.daytrader7/blob/master/docs/Using-cmd-line.md). I am using following OpenLiberty as the server:
```
$ ~/data/wlp/bin/productInfo version
Product name: Open Liberty
Product version: 19.0.0.11
Product edition: Open
```

After the first startup of the application I see following exception in `messages.log`:

```
[11/27/19 16:56:03:368 GMT] 0000002c com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "javax.ejb.EJBTransactionRolledbackException: setRollbackOnly called from within a singleton post construct method. com.ibm.ejs.container.EJSHome.createBeanO 1047" at ffdc_19.11.27_16.56.03.0.log
[11/27/19 16:56:03:373 GMT] 0000002c com.ibm.ejs.container.LocalExceptionMappingStrategy          E CNTR0019E: EJB threw an unexpected (non-declared) exception during invocation of method "updateMarketSummary". Exception data: javax.ejb.NoSuchEJBException: An error occurred during initialization of singleton session bean daytrader7#daytrader-ee7-ejb.jar#MarketSummarySingleton, resulting in the discarding of the singleton instance.; nested exception is: javax.ejb.EJBTransactionRolledbackException: setRollbackOnly called from within a singleton post construct method.
        at com.ibm.ejs.container.util.ExceptionUtil.NoSuchEJBException(ExceptionUtil.java:431)
        at com.ibm.ejs.container.EJSHome.createSingletonBeanO(EJSHome.java:3754)
        at com.ibm.ejs.container.EJSHome.createBeanO(EJSHome.java:936)
        at com.ibm.ejs.container.EJSHome.createBeanO(EJSHome.java:1077)
        at com.ibm.ejs.container.activator.UncachedActivationStrategy.atActivate(UncachedActivationStrategy.java:62)
        at com.ibm.ejs.container.activator.Activator.preInvokeActivateBean(Activator.java:263)
        at com.ibm.ejs.container.EJSContainer.preInvokeActivate(EJSContainer.java:3001)
        at com.ibm.ejs.container.EJSContainer.EjbPreInvoke(EJSContainer.java:2390)
        at com.ibm.ejs.container.TimedObjectWrapper.invokeCallback(TimedObjectWrapper.java:83)
        at com.ibm.ejs.container.TimerNpRunnable.doWork(TimerNpRunnable.java:183)
        at com.ibm.ejs.container.TimerNpRunnable.run(TimerNpRunnable.java:97)
        at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:819)
Caused by: javax.ejb.EJBTransactionRolledbackException: setRollbackOnly called from within a singleton post construct method.
        at com.ibm.ejs.container.EJSContainer.postInvokeForLifecycleInterceptors(EJSContainer.java:4214)
        at com.ibm.ejs.container.SingletonBeanO.callTransactionalLifecycleInterceptors(SingletonBeanO.java:229)
        at com.ibm.ejs.container.SingletonBeanO.initialize(SingletonBeanO.java:307)
        at com.ibm.ejs.container.BeanOFactory.create(BeanOFactory.java:103)
        at com.ibm.ejs.container.EJSHome.createSingletonBeanO(EJSHome.java:3740)
        ... 16 more
```

These messages appear after the log message `The daytrader7Sample server is ready to run a smarter planet.`
Is this expected during the first startup of the application?

**Comment by avash-k** [comment]
while building the docker image from Dockerfile include the environment variables inside the Dockerfile and then give a try 
[Dockerfile.txt](https://github.com/WASdev/sample.daytrader7/files/3977511/Dockerfile.txt)

**Comment by jdmcclur** [comment]
This may happen if the db is not yet loaded (first start). If the database is loaded and you see this, it is a problem.

**Comment by ashu-mehra** [comment]
@jdmcclur I see it only for first time. As per your comment I take that it is expected, so closing this issue.
